train_x_file: data/clean/test_15/train_x.csv
train_y_file: data/clean/test_15/train_y.csv
val_x_file: data/clean/test_15/val_x.csv
val_y_file: data/clean/test_15/val_y.csv
test_x_file: data/clean/test_15/test_x.csv
test_y_file: data/clean/test_15/test_y.csv
embedder: bert
criteria_embedder: identity
combiner: concatenate
alpha: 0.01
beta: 0.01
opt_weight_decay: 0
learning_rate: 0.001
batch_size: 32
num_epochs: 1000
device: cuda
finetune: False
wandb_project: example_debug
experiment_name: lr0.001_wd0.01
train_metrics_path: train_metrics.csv
val_metrics_path: val_metrics.csv
best_model_path: best_model.pth
loss: normal
seed: 360