# Configuration for problem domains
num_domains: 8

problems:
  - name: Problem1
    text: Which plot best represents the acceleration curve associated with the displacement and velocity curves shown here? 
    id: 1
    domains:
      - name: Objects
        id: 1
        num_criteria: 1
      - name: Influences
        id: 2
        num_criteria: 0
      - name: Properties
        id: 3
        num_criteria: 0
      - name: Positioning
        id: 4
        num_criteria: 1
      - name: Movements
        id: 5
        num_criteria: 3
      - name: Interactions
        id: 6
        num_criteria: 0
      - name: Descriptive Relationships
        id: 7
        num_criteria: 2
      - name: Mechanistic Relationships
        id: 8
        num_criteria: 0
  - name: Problem2
    id: 2
    text: A physics demo launches a ball horizontally while dropping a second ball vertically at exactly the same time. 
    domains:
      - name: Objects
        id: 1
        num_criteria: 2
      - name: Influences
        id: 2
        num_criteria: 2
      - name: Properties
        id: 3
        num_criteria: 0
      - name: Positioning
        id: 4
        num_criteria: 2
      - name: Movements
        id: 5
        num_criteria: 2
      - name: Interactions
        id: 6
        num_criteria: 2
      - name: Descriptive Relationships
        id: 7
        num_criteria: 0
      - name: Mechanistic Relationships
        id: 8
        num_criteria: 1
  - name: Problem3
    id: 3
    text: A girls hands on a moving sidewalk (convert belt) that is moving to the right at a speed of 2 m/s relative to the ground. A dog runs on the belt toward the girl at a sped of 8 m/s/ relative to the belt. What is the speed of the god relative to the girl?
    domains:
      - name: Objects
        id: 1
        num_criteria: 3
      - name: Influences
        id: 2
        num_criteria: 0
      - name: Properties
        id: 3
        num_criteria: 0
      - name: Positioning
        id: 4
        num_criteria: 2
      - name: Movements
        id: 5
        num_criteria: 3
      - name: Interactions
        id: 6
        num_criteria: 2
      - name: Descriptive Relationships
        id: 7
        num_criteria: 0
      - name: Mechanistic Relationships
        id: 8
        num_criteria: 1
  - name: Problem4
    id: 4
    text: The net force on the box is in the positive x direction. Which of the following statements best describes the motion of the box?
    domains:
      - name: Objects
        id: 1
        num_criteria: 1
      - name: Influences
        id: 2
        num_criteria: 1
      - name: Properties
        id: 3
        num_criteria: 1
      - name: Positioning
        id: 4
        num_criteria: 2
      - name: Movements
        id: 5
        num_criteria: 2
      - name: Interactions
        id: 6
        num_criteria: 1
      - name: Descriptive Relationships
        id: 7
        num_criteria: 0
      - name: Mechanistic Relationships
        id: 8
        num_criteria: 1

# To index problems and domains in Python, you can use:
# config['problems'][index] for problems
# config['problems'][index]['domains'][index] for domains within a problem